language: scala

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier

env:
  matrix:
    - scriptName=sbtTests-1.0
    - scriptName=integrationTest
    - scriptName=sbtTests-0.13
    - scriptName=s3-integration

deploy:
  on:
    tags: true

after_success:
  - bash ci-scripts/deploy.sh

script:
  - echo Will run ci-scripts/$scriptName.sh
  - if [ -z $TRAVIS_TAG ]; then bash ci-scripts/$scriptName.sh; fi

jdk:
  - oraclejdk8