language: scala

branches:
  only:
  - master

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier

env:
  matrix:
    - scriptName=sbtTests-1.0
    - scriptName=integrationTest
    - scriptName=sbtTests-0.13
    - scriptName=s3-integration

deploy:
  on:
    tags: true

after_success:
  - bash ci-scripts/deploy.sh

script:
  - if [ -z $TRAVIS_TAG ]; then
      echo Will run ci-scripts/$scriptName.sh
      bash ci-scripts/$scriptName.sh
    else
      echo Building tag $TRAVIS_TAG, skipping build
    fi

jdk:
  - oraclejdk8